export const environment = {
  production: false,
  googleMapsKey: 'AIzaSyBuTmQj9nLYKV9jb-Kk_6W2Ue95dfMw8Kc',
  firebaseConfig:  {
    apiKey: "AIzaSyBBa2iIUnEFhKhVHT3wcepiVEl4BOfOOYA",
    authDomain: "taliferro-de66f.firebaseapp.com",
    databaseURL: "https://taliferro-de66f.firebaseio.com",
    projectId: "taliferro-de66f",
    storageBucket: "taliferro-de66f.appspot.com",
    messagingSenderId: "353334442276",
    appId: "1:353334442276:web:45b043204cc83aa7725bb1"
  },
  pracId: 18233,
  locPos: 1,
  billMethod: 'BILL',
  orderedBy: 'tshowers',
  defaultStatus: 0,
  siteType: undefined,
  summaryRedirect: 'http://localhost:4200/identity/email-check',
  savedCartRedirect: 'http://localhost:4200/identity/saved-cart-check',
  localURL: 'http://localhost:4200',
  superDuper: "ty.showers@gmail.com",
  sampleProcessing: undefined,
  CARTS: "carts",
  SAVED_CARTS: "saved-carts",
  CUSTOMERS: "customers",
  CONTACTS: "contacts",
  LAB_ORDERS: "lab-orders",
  ORDERS: "orders",
  PAYMENTS: "payments",
  PRODUCTS: "products",
  DAILY_REPORTS: "daily-reports",
  SETTINGS: "settings",
  TEST_KITS: "test-kits",
  USERS: "users",
  CATEGORIES: "categories",
  LIS_PRACTITIONERS: "lis-practitioners",
  SUB_CATEGORIES: "sub-categories",
  PRODUCT_DEPENDENCIES: "product-dependencies",
  PRODUCT_TYPES: "product-types",
  APPOINTMENTS: "appointments",
  LOGO_PATH: "logo",
  FILE_PATH: "files",
  RESULTS_PATH: "results",
  COMPANY_NAME: "Taliferro Group"

};


